import "./globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";

const poppinsFont = Poppins({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  fallback: ["Arial", "Helvetica", "sens-serif"],
  variable: "--poppins-font"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface IProps {
  children: React.ReactNode;
  latestHealth: React.ReactNode;
  latestSports: React.ReactNode;
}

export default function RootLayout(props: IProps) {
  return (
    <html lang="en">
      <body className={poppinsFont.variable}>
        {props.children}
        {/* <section>{props.latestSports}</section> */}
        {/* <section>{props.latestHealth}</section> */}
      </body>
    </html>
  );
}
