import "./globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
const poppinsFont = Poppins({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  fallback: ["Arial", "Helvetica", "sens-serif"],
  variable: "--poppins-font"
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={poppinsFont.variable}>
        {children}
      </body>
    </html>
  );
}
